#!/usr/bin/bash

WALLPAPER_DIR="$HOME/.config/hypr/theme/walls"
LAST_WALL_FILE="$HOME/.cache/last_wallpaper.txt"

choose_new_wallpaper() {
  local new
  while true; do
    new=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)
    if [[ ! -f "$LAST_WALL_FILE" ]] || [[ "$new" != "$(cat "$LAST_WALL_FILE")" ]]; then
      echo "$new"
      return
    fi
  done
}

WALLPAPER=$(choose_new_wallpaper)

echo "$WALLPAPER" > "$LAST_WALL_FILE"

if pgrep -x "hyprpaper" >/dev/null; then
  hyprctl hyprpaper preload "$WALLPAPER"
  sleep 0.2
  hyprctl hyprpaper wallpaper ",$WALLPAPER"
  notify-send "Wallpaper Changed" -i "$WALLPAPER" --app-name=Wallpaper
fi
